export const TEXTS_UPDATE_TEXT = 'TEXTS_UPDATE_TEXT'
export const TEXTS_SEARCH_SET = 'TEXTS_SEARCH_SET'
export const TEXTS_TAB_SET = 'TEXTS_TAB_SET'
export const TEXTS_SAVING_START = 'TEXTS_SAVING_START'
export const TEXTS_SAVING_END = 'TEXTS_SAVING_END'

export const TEXTS_CHANGE_SET = 'TEXTS_CHANGE_SET'
export const TEXTS_CHANGE_REMOVE = 'TEXTS_CHANGE_REMOVE'
export const TEXTS_CHANGES_RESET = 'TEXTS_CHANGES_RESET'
