seo:
    name: Мета тэги
    values:
        title:
            type: string
            value: seo title
        description:
            type: string
            value: seo description
        sharings:
            name: Картинки для шаринга в соц. сети
            values:
                vk:
                    name: Шаринг для VK
                    type: image
                    value: ''
                tw:
                    name: Шаринг для Twitter
                    type: image
                    value: ''
                fb:
                    name: Шаринг для Facebook
                    type: image
                    value: ''
promo:
    name: Промо-акция
    values:
        toolbar:
            name: Заголовок в шапке
            value: 'утеплитель нового поколения'
        timer:
            name: Таймер
            values:
                time:
                    name: Дата и время
                    type: datetime
                    value: '18:00 30.09.2016'
                text:
                    name: Текст
                    value: 'до завершения<br/>акции осталось'
        steps:
            name: Шаги
            values:
                1: 'Зарегистрируйся<br/>на сайте'
                2: 'Предъяви<br/>промо-код'
                3: 'Получи новый ТеплоKNAUF<br/>для КРОВЛИ и СТЕН'
        buttons:
            name: Кнопки
            values:
                main:
                    name: Кнопка действия
                    value: 'получить сейчас'
                one:
                    name: Себе
                    value: 'Строю себе'
                many:
                    name: Другим
                    value: 'Строю другим'
        terms:
            name: Правила акции
            type: html
            value: ''
links:
    name: 'Ссылки'
    values:
        vk:
            name: Ссылка на vk.com
            type: link
            value: ''
        fb:
            name: Ссылка на facebook.com
            type: link
            value: ''
        tw:
            name: Ссылка на twitter.com
            type: link
            value: ''
        ok:
            name: Ссылка на ok.ru
            type: link
            value: ''

sms:
    name: 'SMS'
    values:
        user:
            name: SMS для покупателя
            value: 'Ваш промо-код #CODE#!'
        seller:
            name: SMS для дилера
            values:
                ok:
                    name: Код прошел проверку
                    value: Код верен. Передайте участнику БЕСПЛАТНУЮ упаковку ТеплоKNAUF
                already:
                    name: Код уже был активирован ранее
                    value: Ошибка. Код был активирован ранее
                false:
                    name: Код не найден
                    value: Код неверен. Проверьте написание и отправьте код снова.
