seo:
    name: 'Мета тэги'
    values:
        title: 'seo title'
        description: 'seo description'
        sharings:
            name: 'Картинки для шаринга в соц. сети'
            values:
                vk:
                    name: 'Шаринг для VK'
                    type: image
                    value: ''
                tw:
                    name: 'Шаринг для Twitter'
                    type: image
                    value: ''
                fb:
                    name: 'Шаринг для Facebook'
                    type: image
                    value: ''
links:
    name: 'Ссылки'
    values:
        vk:
            name: Ссылка на VK.com
            type: link
            value: ''
