seo:
    name: Мета тэги
    values:
        title:
            type: string
            value: seo title
        description:
            type: string
            value: seo description
        sharings:
            name: Картинки для шаринга в соц. сети
            values:
                vk:
                    name: Шаринг для VK
                    type: image
                    value: ''
                tw:
                    name: Шаринг для Twitter
                    type: image
                    value: ''
                fb:
                    name: Шаринг для Facebook
                    type: image
                    value: ''
promo:
    name: Промо-акция
    values:
        timer:
            name: Дата и время для таймера
            type: datetime
            value: ''
        terms:
            name: Правила акции
            type: html
            value: ''
links:
    name: 'Ссылки'
    values:
        vk:
            name: Ссылка на vk.com
            type: link
            value: ''
        fb:
            name: Ссылка на facebook.com
            type: link
            value: ''
        tw:
            name: Ссылка на twitter.com
            type: link
            value: ''
        ok:
            name: Ссылка на ok.ru
            type: link
            value: ''

sms:
    name: 'SMS'
    values:
        user:
            name: SMS для покупателя
            value: 'Ваш промо-код #CODE#!'
        seller:
            name: SMS для дилера
            values:
                ok:
                    name: Код прошел проверку
                    value: Код прошел проверку
                already:
                    name: Код уже был активирован ранее
                    value: Код уже был активирован ранее
                false:
                    name: Код не найден
                    value: Код не найден
